#!/bin/bash
# update yum just in case
apt-get install update
# get node into yum
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
# install node and npm in one line
apt-get install -y nodejs
# install pm2 to restart node app
npm i -g pm2@2.4.3
